language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
    - oraclejdk8
script:
    - ./gradlew clean build
sudo: false
